### ISSUE TITLE
Given that tamagui is iterating quickly, set tamagui peerDependencies to *

### ISSUE THREAD

**Issue by openefit** [lobor/tamagui-react-hook-form#4]
I just upgraded to version 0.3 and got the following error:
> Could not resolve dependency:
npm ERR! peer tamagui@"1.15.37" from tamagui-react-hook-form@0.3.0

**Comment by lobor** [comment]
tamagui is a peer dependencies, so you should install tamagui-react-hook-form where you install tamagui
in tamagui starter should be in `packages/ui`

**Comment by openefit** [comment]
tamagui-react-hook-form@0.3.0 specifies a specific version of tamagui@1.15.37, rather than using a wildcard `*`.
![截图 2023-05-02 23-33-13](https://user-images.githubusercontent.com/9696164/235714629-645a70d4-9760-4924-90f4-bd14f568fabd.png)

**Comment by lobor** [comment]
oh ok, i did not understand. i will change it asap

**Comment by lobor** [comment]
fix on 0.3.1 https://github.com/lobor/tamagui-react-hook-form/commit/f5915ec95723a4eb458005f17e67023b149ec47d
